//console.log(a);
//on the avobe code of block it will through a arror because a is not define 
//that's we use try and catch to find error in code of block

try{
    console.log(a);
}
catch(error){
    console.log(error);

}